name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore DbStudio.sln

      - name: Build solution
        run: dotnet build DbStudio.sln --configuration ${{ matrix.configuration }} --no-restore

      - name: Run tests
        run: dotnet test DbStudio.sln --configuration ${{ matrix.configuration }} --no-build --verbosity normal
